name: CI/CD PHP Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Vérifier PHP
        run: C:\wamp64\bin\php\php8.0.30\php.exe -v

      - name: Déployer vers WAMP
        run: xcopy /E /I /Y * "C:\wamp64\www\memoire\"

      - name: Fin
        run: echo "Déploiement terminé ✅"