name: CI/CD Application PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      # 1. Récupération du code
      - name: Récupération du code
        uses: actions/checkout@v4

      # 2. Version PHP
      - name: Vérification PHP
        run: php -v

      # 3. Installation dépendances Composer
      - name: Installation des dépendances
        run: composer install --no-interaction --prefer-dist

      # 4. Lancement des tests PHPUnit
      - name: Tests unitaires
        run: vendor/bin/phpunit tests --testdox

      # 5. Correction automatique du style (PHPCBF)
      - name: Correction du style de code (PHPCBF)
        run: vendor/bin/phpcbf --standard=PSR12 --ignore=vendor .
        continue-on-error: true

      # 6. Vérification du style (PHPCS)
      - name: Vérification du style de code (PHPCS)
        run: vendor/bin/phpcs --standard=PSR12 --ignore=vendor .
        continue-on-error: true

  deploy:
    needs: build-test
    runs-on: self-hosted

    steps:
      # 7. Déploiement vers WAMP
      - name: Déploiement vers WAMP
        run: |
          echo "Déploiement en cours..."
          robocopy . C:\wamp64\www\memoire /MIR /XD .git vendor tests
          echo "Déploiement terminé"