name: CI/CD Application PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Vérification PHP
        run: php -v

      - name: Installation des dependances
        run: composer install --no-interaction --prefer-dist

      - name: Tests PHPUnit
        run: vendor/bin/phpunit tests --testdox

      - name: Correction style (PHPCBF)
        run: vendor/bin/phpcbf --standard=phpcs.xml .
        continue-on-error: true

      - name: Vérification style (PHPCS)
        run: vendor/bin/phpcs --standard=phpcs.xml .
        continue-on-error: true

  deploy:
    needs: build-test
    runs-on: self-hosted

    steps:

      - name: Deploiement vers WAMP
        shell: cmd
        run: |
          echo Deploiement en cours...
          robocopy . C:\wamp64\www\memoire /MIR /XD .git vendor tests
          echo Deploiement termine
          exit 0